### ISSUE TITLE
ImportError: cannot import name CheckboxChoiceInput

### ISSUE THREAD

**Issue by kliner** [Nekmo/djangocms-comments#14]
python 2.7, Django 1.11.16, v0.2.3, when run # python manage.py migrate after updating the settings, it showes:

```
# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/root/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/env/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/root/env/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/root/env/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/root/env/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/env/lib/python2.7/site-packages/djangocms_comments-0.2.3-py2.7.egg/djangocms_comments/admin.py", line 14, in <module>
    from djangocms_comments.fields import SubmitButtonField, MultipleSubmitButtonRendered, MultipleSubmitButton, \
  File "/root/env/lib/python2.7/site-packages/djangocms_comments-0.2.3-py2.7.egg/djangocms_comments/fields.py", line 5, in <module>
    from django.forms.widgets import CheckboxChoiceInput, ChoiceFieldRenderer, RadioChoiceInput, SubWidget, RendererMixin, \
```

**Comment by max-kubierschky** [comment]
I have the same problem. Did you get any further?

**Comment by max-kubierschky** [comment]
The cause is, that CheckboxChoiceInput and others have been removed in django 1.11, see:  https://docs.djangoproject.com/en/1.11/releases/1.11/#changes-due-to-the-introduction-of-template-based-widget-rendering . I do not have a solution yet.

**Comment by ckangnz** [comment]
If you see the updated django.forms.widgets in 1.11 version, we can see the available form inputs are 

```
 'Media', 'MediaDefiningClass', 'Widget', 'TextInput', 'NumberInput',
    'EmailInput', 'URLInput', 'PasswordInput', 'HiddenInput',
    'MultipleHiddenInput', 'FileInput', 'ClearableFileInput', 'Textarea',
    'DateInput', 'DateTimeInput', 'TimeInput', 'CheckboxInput', 'Select',
    'NullBooleanSelect', 'SelectMultiple', 'RadioSelect',
    'CheckboxSelectMultiple', 'MultiWidget', 'SplitDateTimeWidget',
    'SplitHiddenDateTimeWidget', 'SelectDateWidget',
```

Probably changing `CheckboxChoiceInput` to `CheckboxInput` could work?

Edit: Just realised `CheckboxChoiceInput` isn't the only issue here..

**Comment by saikirubamj** [comment]
Any solutions for this issues
